<?php

/**
 * Implements hook_menu().
 */
function profile_subscriptions_menu() {
  $items['user/%user/subscriptions'] = [
    'title' => t('Subscriptions'),
    'description' => t('Subscriptions menu'),
    'type' => MENU_LOCAL_TASK,
    'page callback' => 'drupal_get_form',
    'page arguments' => array('user_profile_form', 1, 'account', 'some_flag'),
    'access callback' => 'user_is_logged_in',
    'expanded' => TRUE,
    'weight' => '10',
    'file' => 'user.pages.inc',
    'file path' => drupal_get_path('module', 'user'),
  ];

  return $items;
}
